/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TubDoorsDothtmlRouteImport } from './routes/tub-doors[.]html'
import { Route as ShowerEnclosuresDothtmlRouteImport } from './routes/shower-enclosures[.]html'
import { Route as ShowerDoorsDothtmlRouteImport } from './routes/shower-doors[.]html'
import { Route as ShowerDoorsSchaumburgIlDothtmlRouteImport } from './routes/shower-doors-schaumburg-il[.]html'
import { Route as ShowerDoorsPalatineIlDothtmlRouteImport } from './routes/shower-doors-palatine-il[.]html'
import { Route as ShowerDoorsHoffmanEstatesIlDothtmlRouteImport } from './routes/shower-doors-hoffman-estates-il[.]html'
import { Route as ShowerDoorsElkGroveVillageIlDothtmlRouteImport } from './routes/shower-doors-elk-grove-village-il[.]html'
import { Route as ShowerDoorsArlingtonHeightsIlDothtmlRouteImport } from './routes/shower-doors-arlington-heights-il[.]html'
import { Route as ReplacementGlassDothtmlRouteImport } from './routes/replacement-glass[.]html'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as FramelessVsSemiFramelessShowerDoorsDothtmlRouteImport } from './routes/frameless-vs-semi-frameless-shower-doors[.]html'
import { Route as CustomShowerGlassDothtmlRouteImport } from './routes/custom-shower-glass[.]html'
import { Route as BathroomRemodelGlassDothtmlRouteImport } from './routes/bathroom-remodel-glass[.]html'
import { Route as IndexRouteImport } from './routes/index'

const TubDoorsDothtmlRoute = TubDoorsDothtmlRouteImport.update({
  id: '/tub-doors.html',
  path: '/tub-doors.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowerEnclosuresDothtmlRoute = ShowerEnclosuresDothtmlRouteImport.update({
  id: '/shower-enclosures.html',
  path: '/shower-enclosures.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowerDoorsDothtmlRoute = ShowerDoorsDothtmlRouteImport.update({
  id: '/shower-doors.html',
  path: '/shower-doors.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowerDoorsSchaumburgIlDothtmlRoute =
  ShowerDoorsSchaumburgIlDothtmlRouteImport.update({
    id: '/shower-doors-schaumburg-il.html',
    path: '/shower-doors-schaumburg-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsPalatineIlDothtmlRoute =
  ShowerDoorsPalatineIlDothtmlRouteImport.update({
    id: '/shower-doors-palatine-il.html',
    path: '/shower-doors-palatine-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsHoffmanEstatesIlDothtmlRoute =
  ShowerDoorsHoffmanEstatesIlDothtmlRouteImport.update({
    id: '/shower-doors-hoffman-estates-il.html',
    path: '/shower-doors-hoffman-estates-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsElkGroveVillageIlDothtmlRoute =
  ShowerDoorsElkGroveVillageIlDothtmlRouteImport.update({
    id: '/shower-doors-elk-grove-village-il.html',
    path: '/shower-doors-elk-grove-village-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsArlingtonHeightsIlDothtmlRoute =
  ShowerDoorsArlingtonHeightsIlDothtmlRouteImport.update({
    id: '/shower-doors-arlington-heights-il.html',
    path: '/shower-doors-arlington-heights-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReplacementGlassDothtmlRoute = ReplacementGlassDothtmlRouteImport.update({
  id: '/replacement-glass.html',
  path: '/replacement-glass.html',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const FramelessVsSemiFramelessShowerDoorsDothtmlRoute =
  FramelessVsSemiFramelessShowerDoorsDothtmlRouteImport.update({
    id: '/frameless-vs-semi-frameless-shower-doors.html',
    path: '/frameless-vs-semi-frameless-shower-doors.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomShowerGlassDothtmlRoute =
  CustomShowerGlassDothtmlRouteImport.update({
    id: '/custom-shower-glass.html',
    path: '/custom-shower-glass.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const BathroomRemodelGlassDothtmlRoute =
  BathroomRemodelGlassDothtmlRouteImport.update({
    id: '/bathroom-remodel-glass.html',
    path: '/bathroom-remodel-glass.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bathroom-remodel-glass.html': typeof BathroomRemodelGlassDothtmlRoute
  '/custom-shower-glass.html': typeof CustomShowerGlassDothtmlRoute
  '/frameless-vs-semi-frameless-shower-doors.html': typeof FramelessVsSemiFramelessShowerDoorsDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/replacement-glass.html': typeof ReplacementGlassDothtmlRoute
  '/shower-doors-arlington-heights-il.html': typeof ShowerDoorsArlingtonHeightsIlDothtmlRoute
  '/shower-doors-elk-grove-village-il.html': typeof ShowerDoorsElkGroveVillageIlDothtmlRoute
  '/shower-doors-hoffman-estates-il.html': typeof ShowerDoorsHoffmanEstatesIlDothtmlRoute
  '/shower-doors-palatine-il.html': typeof ShowerDoorsPalatineIlDothtmlRoute
  '/shower-doors-schaumburg-il.html': typeof ShowerDoorsSchaumburgIlDothtmlRoute
  '/shower-doors.html': typeof ShowerDoorsDothtmlRoute
  '/shower-enclosures.html': typeof ShowerEnclosuresDothtmlRoute
  '/tub-doors.html': typeof TubDoorsDothtmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bathroom-remodel-glass.html': typeof BathroomRemodelGlassDothtmlRoute
  '/custom-shower-glass.html': typeof CustomShowerGlassDothtmlRoute
  '/frameless-vs-semi-frameless-shower-doors.html': typeof FramelessVsSemiFramelessShowerDoorsDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/replacement-glass.html': typeof ReplacementGlassDothtmlRoute
  '/shower-doors-arlington-heights-il.html': typeof ShowerDoorsArlingtonHeightsIlDothtmlRoute
  '/shower-doors-elk-grove-village-il.html': typeof ShowerDoorsElkGroveVillageIlDothtmlRoute
  '/shower-doors-hoffman-estates-il.html': typeof ShowerDoorsHoffmanEstatesIlDothtmlRoute
  '/shower-doors-palatine-il.html': typeof ShowerDoorsPalatineIlDothtmlRoute
  '/shower-doors-schaumburg-il.html': typeof ShowerDoorsSchaumburgIlDothtmlRoute
  '/shower-doors.html': typeof ShowerDoorsDothtmlRoute
  '/shower-enclosures.html': typeof ShowerEnclosuresDothtmlRoute
  '/tub-doors.html': typeof TubDoorsDothtmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bathroom-remodel-glass.html': typeof BathroomRemodelGlassDothtmlRoute
  '/custom-shower-glass.html': typeof CustomShowerGlassDothtmlRoute
  '/frameless-vs-semi-frameless-shower-doors.html': typeof FramelessVsSemiFramelessShowerDoorsDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/replacement-glass.html': typeof ReplacementGlassDothtmlRoute
  '/shower-doors-arlington-heights-il.html': typeof ShowerDoorsArlingtonHeightsIlDothtmlRoute
  '/shower-doors-elk-grove-village-il.html': typeof ShowerDoorsElkGroveVillageIlDothtmlRoute
  '/shower-doors-hoffman-estates-il.html': typeof ShowerDoorsHoffmanEstatesIlDothtmlRoute
  '/shower-doors-palatine-il.html': typeof ShowerDoorsPalatineIlDothtmlRoute
  '/shower-doors-schaumburg-il.html': typeof ShowerDoorsSchaumburgIlDothtmlRoute
  '/shower-doors.html': typeof ShowerDoorsDothtmlRoute
  '/shower-enclosures.html': typeof ShowerEnclosuresDothtmlRoute
  '/tub-doors.html': typeof TubDoorsDothtmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bathroom-remodel-glass.html'
    | '/custom-shower-glass.html'
    | '/frameless-vs-semi-frameless-shower-doors.html'
    | '/index.html'
    | '/replacement-glass.html'
    | '/shower-doors-arlington-heights-il.html'
    | '/shower-doors-elk-grove-village-il.html'
    | '/shower-doors-hoffman-estates-il.html'
    | '/shower-doors-palatine-il.html'
    | '/shower-doors-schaumburg-il.html'
    | '/shower-doors.html'
    | '/shower-enclosures.html'
    | '/tub-doors.html'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bathroom-remodel-glass.html'
    | '/custom-shower-glass.html'
    | '/frameless-vs-semi-frameless-shower-doors.html'
    | '/index.html'
    | '/replacement-glass.html'
    | '/shower-doors-arlington-heights-il.html'
    | '/shower-doors-elk-grove-village-il.html'
    | '/shower-doors-hoffman-estates-il.html'
    | '/shower-doors-palatine-il.html'
    | '/shower-doors-schaumburg-il.html'
    | '/shower-doors.html'
    | '/shower-enclosures.html'
    | '/tub-doors.html'
  id:
    | '__root__'
    | '/'
    | '/bathroom-remodel-glass.html'
    | '/custom-shower-glass.html'
    | '/frameless-vs-semi-frameless-shower-doors.html'
    | '/index.html'
    | '/replacement-glass.html'
    | '/shower-doors-arlington-heights-il.html'
    | '/shower-doors-elk-grove-village-il.html'
    | '/shower-doors-hoffman-estates-il.html'
    | '/shower-doors-palatine-il.html'
    | '/shower-doors-schaumburg-il.html'
    | '/shower-doors.html'
    | '/shower-enclosures.html'
    | '/tub-doors.html'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BathroomRemodelGlassDothtmlRoute: typeof BathroomRemodelGlassDothtmlRoute
  CustomShowerGlassDothtmlRoute: typeof CustomShowerGlassDothtmlRoute
  FramelessVsSemiFramelessShowerDoorsDothtmlRoute: typeof FramelessVsSemiFramelessShowerDoorsDothtmlRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  ReplacementGlassDothtmlRoute: typeof ReplacementGlassDothtmlRoute
  ShowerDoorsArlingtonHeightsIlDothtmlRoute: typeof ShowerDoorsArlingtonHeightsIlDothtmlRoute
  ShowerDoorsElkGroveVillageIlDothtmlRoute: typeof ShowerDoorsElkGroveVillageIlDothtmlRoute
  ShowerDoorsHoffmanEstatesIlDothtmlRoute: typeof ShowerDoorsHoffmanEstatesIlDothtmlRoute
  ShowerDoorsPalatineIlDothtmlRoute: typeof ShowerDoorsPalatineIlDothtmlRoute
  ShowerDoorsSchaumburgIlDothtmlRoute: typeof ShowerDoorsSchaumburgIlDothtmlRoute
  ShowerDoorsDothtmlRoute: typeof ShowerDoorsDothtmlRoute
  ShowerEnclosuresDothtmlRoute: typeof ShowerEnclosuresDothtmlRoute
  TubDoorsDothtmlRoute: typeof TubDoorsDothtmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tub-doors.html': {
      id: '/tub-doors.html'
      path: '/tub-doors.html'
      fullPath: '/tub-doors.html'
      preLoaderRoute: typeof TubDoorsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-enclosures.html': {
      id: '/shower-enclosures.html'
      path: '/shower-enclosures.html'
      fullPath: '/shower-enclosures.html'
      preLoaderRoute: typeof ShowerEnclosuresDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors.html': {
      id: '/shower-doors.html'
      path: '/shower-doors.html'
      fullPath: '/shower-doors.html'
      preLoaderRoute: typeof ShowerDoorsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-schaumburg-il.html': {
      id: '/shower-doors-schaumburg-il.html'
      path: '/shower-doors-schaumburg-il.html'
      fullPath: '/shower-doors-schaumburg-il.html'
      preLoaderRoute: typeof ShowerDoorsSchaumburgIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-palatine-il.html': {
      id: '/shower-doors-palatine-il.html'
      path: '/shower-doors-palatine-il.html'
      fullPath: '/shower-doors-palatine-il.html'
      preLoaderRoute: typeof ShowerDoorsPalatineIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-hoffman-estates-il.html': {
      id: '/shower-doors-hoffman-estates-il.html'
      path: '/shower-doors-hoffman-estates-il.html'
      fullPath: '/shower-doors-hoffman-estates-il.html'
      preLoaderRoute: typeof ShowerDoorsHoffmanEstatesIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-elk-grove-village-il.html': {
      id: '/shower-doors-elk-grove-village-il.html'
      path: '/shower-doors-elk-grove-village-il.html'
      fullPath: '/shower-doors-elk-grove-village-il.html'
      preLoaderRoute: typeof ShowerDoorsElkGroveVillageIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-arlington-heights-il.html': {
      id: '/shower-doors-arlington-heights-il.html'
      path: '/shower-doors-arlington-heights-il.html'
      fullPath: '/shower-doors-arlington-heights-il.html'
      preLoaderRoute: typeof ShowerDoorsArlingtonHeightsIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replacement-glass.html': {
      id: '/replacement-glass.html'
      path: '/replacement-glass.html'
      fullPath: '/replacement-glass.html'
      preLoaderRoute: typeof ReplacementGlassDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameless-vs-semi-frameless-shower-doors.html': {
      id: '/frameless-vs-semi-frameless-shower-doors.html'
      path: '/frameless-vs-semi-frameless-shower-doors.html'
      fullPath: '/frameless-vs-semi-frameless-shower-doors.html'
      preLoaderRoute: typeof FramelessVsSemiFramelessShowerDoorsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-shower-glass.html': {
      id: '/custom-shower-glass.html'
      path: '/custom-shower-glass.html'
      fullPath: '/custom-shower-glass.html'
      preLoaderRoute: typeof CustomShowerGlassDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-remodel-glass.html': {
      id: '/bathroom-remodel-glass.html'
      path: '/bathroom-remodel-glass.html'
      fullPath: '/bathroom-remodel-glass.html'
      preLoaderRoute: typeof BathroomRemodelGlassDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BathroomRemodelGlassDothtmlRoute: BathroomRemodelGlassDothtmlRoute,
  CustomShowerGlassDothtmlRoute: CustomShowerGlassDothtmlRoute,
  FramelessVsSemiFramelessShowerDoorsDothtmlRoute:
    FramelessVsSemiFramelessShowerDoorsDothtmlRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
  ReplacementGlassDothtmlRoute: ReplacementGlassDothtmlRoute,
  ShowerDoorsArlingtonHeightsIlDothtmlRoute:
    ShowerDoorsArlingtonHeightsIlDothtmlRoute,
  ShowerDoorsElkGroveVillageIlDothtmlRoute:
    ShowerDoorsElkGroveVillageIlDothtmlRoute,
  ShowerDoorsHoffmanEstatesIlDothtmlRoute:
    ShowerDoorsHoffmanEstatesIlDothtmlRoute,
  ShowerDoorsPalatineIlDothtmlRoute: ShowerDoorsPalatineIlDothtmlRoute,
  ShowerDoorsSchaumburgIlDothtmlRoute: ShowerDoorsSchaumburgIlDothtmlRoute,
  ShowerDoorsDothtmlRoute: ShowerDoorsDothtmlRoute,
  ShowerEnclosuresDothtmlRoute: ShowerEnclosuresDothtmlRoute,
  TubDoorsDothtmlRoute: TubDoorsDothtmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
