/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WineCigarRoomsDothtmlRouteImport } from './routes/wine-cigar-rooms[.]html'
import { Route as WineCigarRoomGlassGuideDothtmlRouteImport } from './routes/wine-cigar-room-glass-guide[.]html'
import { Route as TubDoorsDothtmlRouteImport } from './routes/tub-doors[.]html'
import { Route as TubDoorBuyersGuideDothtmlRouteImport } from './routes/tub-door-buyers-guide[.]html'
import { Route as ShowerEnclosuresDothtmlRouteImport } from './routes/shower-enclosures[.]html'
import { Route as ShowerEnclosureBuyersGuideDothtmlRouteImport } from './routes/shower-enclosure-buyers-guide[.]html'
import { Route as ShowerDoorsDothtmlRouteImport } from './routes/shower-doors[.]html'
import { Route as ShowerDoorsWinnetkaIlDothtmlRouteImport } from './routes/shower-doors-winnetka-il[.]html'
import { Route as ShowerDoorsWilmetteIlDothtmlRouteImport } from './routes/shower-doors-wilmette-il[.]html'
import { Route as ShowerDoorsWheelingIlDothtmlRouteImport } from './routes/shower-doors-wheeling-il[.]html'
import { Route as ShowerDoorsVernonHillsIlDothtmlRouteImport } from './routes/shower-doors-vernon-hills-il[.]html'
import { Route as ShowerDoorsStreamwoodIlDothtmlRouteImport } from './routes/shower-doors-streamwood-il[.]html'
import { Route as ShowerDoorsSkokieIlDothtmlRouteImport } from './routes/shower-doors-skokie-il[.]html'
import { Route as ShowerDoorsRoselleIlDothtmlRouteImport } from './routes/shower-doors-roselle-il[.]html'
import { Route as ShowerDoorsRollingMeadowsIlDothtmlRouteImport } from './routes/shower-doors-rolling-meadows-il[.]html'
import { Route as ShowerDoorsRiverwoodsIlDothtmlRouteImport } from './routes/shower-doors-riverwoods-il[.]html'
import { Route as ShowerDoorsParkRidgeIlDothtmlRouteImport } from './routes/shower-doors-park-ridge-il[.]html'
import { Route as ShowerDoorsPalatineIlDothtmlRouteImport } from './routes/shower-doors-palatine-il[.]html'
import { Route as ShowerDoorsNorthfieldIlDothtmlRouteImport } from './routes/shower-doors-northfield-il[.]html'
import { Route as ShowerDoorsNorthbrookIlDothtmlRouteImport } from './routes/shower-doors-northbrook-il[.]html'
import { Route as ShowerDoorsMountProspectIlDothtmlRouteImport } from './routes/shower-doors-mount-prospect-il[.]html'
import { Route as ShowerDoorsLincolnshireIlDothtmlRouteImport } from './routes/shower-doors-lincolnshire-il[.]html'
import { Route as ShowerDoorsLibertyvilleIlDothtmlRouteImport } from './routes/shower-doors-libertyville-il[.]html'
import { Route as ShowerDoorsLakeForestIlDothtmlRouteImport } from './routes/shower-doors-lake-forest-il[.]html'
import { Route as ShowerDoorsHoffmanEstatesIlDothtmlRouteImport } from './routes/shower-doors-hoffman-estates-il[.]html'
import { Route as ShowerDoorsHighlandParkIlDothtmlRouteImport } from './routes/shower-doors-highland-park-il[.]html'
import { Route as ShowerDoorsHanoverParkIlDothtmlRouteImport } from './routes/shower-doors-hanover-park-il[.]html'
import { Route as ShowerDoorsGlenviewIlDothtmlRouteImport } from './routes/shower-doors-glenview-il[.]html'
import { Route as ShowerDoorsGlencoeIlDothtmlRouteImport } from './routes/shower-doors-glencoe-il[.]html'
import { Route as ShowerDoorsEvanstonIlDothtmlRouteImport } from './routes/shower-doors-evanston-il[.]html'
import { Route as ShowerDoorsElkGroveVillageIlDothtmlRouteImport } from './routes/shower-doors-elk-grove-village-il[.]html'
import { Route as ShowerDoorsDesPlainesIlDothtmlRouteImport } from './routes/shower-doors-des-plaines-il[.]html'
import { Route as ShowerDoorsDeerfieldIlDothtmlRouteImport } from './routes/shower-doors-deerfield-il[.]html'
import { Route as ShowerDoorsBuffaloGroveIlDothtmlRouteImport } from './routes/shower-doors-buffalo-grove-il[.]html'
import { Route as ShowerDoorsBartlettIlDothtmlRouteImport } from './routes/shower-doors-bartlett-il[.]html'
import { Route as ShowerDoorsBannockburnIlDothtmlRouteImport } from './routes/shower-doors-bannockburn-il[.]html'
import { Route as ShowerDoorsArlingtonHeightsIlDothtmlRouteImport } from './routes/shower-doors-arlington-heights-il[.]html'
import { Route as ShowerDoorBuyersGuideDothtmlRouteImport } from './routes/shower-door-buyers-guide[.]html'
import { Route as ReplacementGlassDothtmlRouteImport } from './routes/replacement-glass[.]html'
import { Route as ReplacementGlassGuideDothtmlRouteImport } from './routes/replacement-glass-guide[.]html'
import { Route as RemodelingDothtmlRouteImport } from './routes/remodeling[.]html'
import { Route as OtherCustomGlassDothtmlRouteImport } from './routes/other-custom-glass[.]html'
import { Route as OtherCustomGlassGuideDothtmlRouteImport } from './routes/other-custom-glass-guide[.]html'
import { Route as OfficePartitionsDothtmlRouteImport } from './routes/office-partitions[.]html'
import { Route as OfficePartitionsGuideDothtmlRouteImport } from './routes/office-partitions-guide[.]html'
import { Route as MirrorsDothtmlRouteImport } from './routes/mirrors[.]html'
import { Route as MirrorsBuyersGuideDothtmlRouteImport } from './routes/mirrors-buyers-guide[.]html'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as GlassRailingsDothtmlRouteImport } from './routes/glass-railings[.]html'
import { Route as GlassRailingsBuyersGuideDothtmlRouteImport } from './routes/glass-railings-buyers-guide[.]html'
import { Route as FramelessVsSemiFramelessShowerDoorsDothtmlRouteImport } from './routes/frameless-vs-semi-frameless-shower-doors[.]html'
import { Route as CustomShowerGlassDothtmlRouteImport } from './routes/custom-shower-glass[.]html'
import { Route as CustomShowerGlassGuideDothtmlRouteImport } from './routes/custom-shower-glass-guide[.]html'
import { Route as BathroomRemodelGlassDothtmlRouteImport } from './routes/bathroom-remodel-glass[.]html'
import { Route as BathroomRemodelGlassGuideDothtmlRouteImport } from './routes/bathroom-remodel-glass-guide[.]html'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const WineCigarRoomsDothtmlRoute = WineCigarRoomsDothtmlRouteImport.update({
  id: '/wine-cigar-rooms.html',
  path: '/wine-cigar-rooms.html',
  getParentRoute: () => rootRouteImport,
} as any)
const WineCigarRoomGlassGuideDothtmlRoute =
  WineCigarRoomGlassGuideDothtmlRouteImport.update({
    id: '/wine-cigar-room-glass-guide.html',
    path: '/wine-cigar-room-glass-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const TubDoorsDothtmlRoute = TubDoorsDothtmlRouteImport.update({
  id: '/tub-doors.html',
  path: '/tub-doors.html',
  getParentRoute: () => rootRouteImport,
} as any)
const TubDoorBuyersGuideDothtmlRoute =
  TubDoorBuyersGuideDothtmlRouteImport.update({
    id: '/tub-door-buyers-guide.html',
    path: '/tub-door-buyers-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerEnclosuresDothtmlRoute = ShowerEnclosuresDothtmlRouteImport.update({
  id: '/shower-enclosures.html',
  path: '/shower-enclosures.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowerEnclosureBuyersGuideDothtmlRoute =
  ShowerEnclosureBuyersGuideDothtmlRouteImport.update({
    id: '/shower-enclosure-buyers-guide.html',
    path: '/shower-enclosure-buyers-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsDothtmlRoute = ShowerDoorsDothtmlRouteImport.update({
  id: '/shower-doors.html',
  path: '/shower-doors.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowerDoorsWinnetkaIlDothtmlRoute =
  ShowerDoorsWinnetkaIlDothtmlRouteImport.update({
    id: '/shower-doors-winnetka-il.html',
    path: '/shower-doors-winnetka-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsWilmetteIlDothtmlRoute =
  ShowerDoorsWilmetteIlDothtmlRouteImport.update({
    id: '/shower-doors-wilmette-il.html',
    path: '/shower-doors-wilmette-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsWheelingIlDothtmlRoute =
  ShowerDoorsWheelingIlDothtmlRouteImport.update({
    id: '/shower-doors-wheeling-il.html',
    path: '/shower-doors-wheeling-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsVernonHillsIlDothtmlRoute =
  ShowerDoorsVernonHillsIlDothtmlRouteImport.update({
    id: '/shower-doors-vernon-hills-il.html',
    path: '/shower-doors-vernon-hills-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsStreamwoodIlDothtmlRoute =
  ShowerDoorsStreamwoodIlDothtmlRouteImport.update({
    id: '/shower-doors-streamwood-il.html',
    path: '/shower-doors-streamwood-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsSkokieIlDothtmlRoute =
  ShowerDoorsSkokieIlDothtmlRouteImport.update({
    id: '/shower-doors-skokie-il.html',
    path: '/shower-doors-skokie-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsRoselleIlDothtmlRoute =
  ShowerDoorsRoselleIlDothtmlRouteImport.update({
    id: '/shower-doors-roselle-il.html',
    path: '/shower-doors-roselle-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsRollingMeadowsIlDothtmlRoute =
  ShowerDoorsRollingMeadowsIlDothtmlRouteImport.update({
    id: '/shower-doors-rolling-meadows-il.html',
    path: '/shower-doors-rolling-meadows-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsRiverwoodsIlDothtmlRoute =
  ShowerDoorsRiverwoodsIlDothtmlRouteImport.update({
    id: '/shower-doors-riverwoods-il.html',
    path: '/shower-doors-riverwoods-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsParkRidgeIlDothtmlRoute =
  ShowerDoorsParkRidgeIlDothtmlRouteImport.update({
    id: '/shower-doors-park-ridge-il.html',
    path: '/shower-doors-park-ridge-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsPalatineIlDothtmlRoute =
  ShowerDoorsPalatineIlDothtmlRouteImport.update({
    id: '/shower-doors-palatine-il.html',
    path: '/shower-doors-palatine-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsNorthfieldIlDothtmlRoute =
  ShowerDoorsNorthfieldIlDothtmlRouteImport.update({
    id: '/shower-doors-northfield-il.html',
    path: '/shower-doors-northfield-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsNorthbrookIlDothtmlRoute =
  ShowerDoorsNorthbrookIlDothtmlRouteImport.update({
    id: '/shower-doors-northbrook-il.html',
    path: '/shower-doors-northbrook-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsMountProspectIlDothtmlRoute =
  ShowerDoorsMountProspectIlDothtmlRouteImport.update({
    id: '/shower-doors-mount-prospect-il.html',
    path: '/shower-doors-mount-prospect-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsLincolnshireIlDothtmlRoute =
  ShowerDoorsLincolnshireIlDothtmlRouteImport.update({
    id: '/shower-doors-lincolnshire-il.html',
    path: '/shower-doors-lincolnshire-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsLibertyvilleIlDothtmlRoute =
  ShowerDoorsLibertyvilleIlDothtmlRouteImport.update({
    id: '/shower-doors-libertyville-il.html',
    path: '/shower-doors-libertyville-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsLakeForestIlDothtmlRoute =
  ShowerDoorsLakeForestIlDothtmlRouteImport.update({
    id: '/shower-doors-lake-forest-il.html',
    path: '/shower-doors-lake-forest-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsHoffmanEstatesIlDothtmlRoute =
  ShowerDoorsHoffmanEstatesIlDothtmlRouteImport.update({
    id: '/shower-doors-hoffman-estates-il.html',
    path: '/shower-doors-hoffman-estates-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsHighlandParkIlDothtmlRoute =
  ShowerDoorsHighlandParkIlDothtmlRouteImport.update({
    id: '/shower-doors-highland-park-il.html',
    path: '/shower-doors-highland-park-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsHanoverParkIlDothtmlRoute =
  ShowerDoorsHanoverParkIlDothtmlRouteImport.update({
    id: '/shower-doors-hanover-park-il.html',
    path: '/shower-doors-hanover-park-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsGlenviewIlDothtmlRoute =
  ShowerDoorsGlenviewIlDothtmlRouteImport.update({
    id: '/shower-doors-glenview-il.html',
    path: '/shower-doors-glenview-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsGlencoeIlDothtmlRoute =
  ShowerDoorsGlencoeIlDothtmlRouteImport.update({
    id: '/shower-doors-glencoe-il.html',
    path: '/shower-doors-glencoe-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsEvanstonIlDothtmlRoute =
  ShowerDoorsEvanstonIlDothtmlRouteImport.update({
    id: '/shower-doors-evanston-il.html',
    path: '/shower-doors-evanston-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsElkGroveVillageIlDothtmlRoute =
  ShowerDoorsElkGroveVillageIlDothtmlRouteImport.update({
    id: '/shower-doors-elk-grove-village-il.html',
    path: '/shower-doors-elk-grove-village-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsDesPlainesIlDothtmlRoute =
  ShowerDoorsDesPlainesIlDothtmlRouteImport.update({
    id: '/shower-doors-des-plaines-il.html',
    path: '/shower-doors-des-plaines-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsDeerfieldIlDothtmlRoute =
  ShowerDoorsDeerfieldIlDothtmlRouteImport.update({
    id: '/shower-doors-deerfield-il.html',
    path: '/shower-doors-deerfield-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsBuffaloGroveIlDothtmlRoute =
  ShowerDoorsBuffaloGroveIlDothtmlRouteImport.update({
    id: '/shower-doors-buffalo-grove-il.html',
    path: '/shower-doors-buffalo-grove-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsBartlettIlDothtmlRoute =
  ShowerDoorsBartlettIlDothtmlRouteImport.update({
    id: '/shower-doors-bartlett-il.html',
    path: '/shower-doors-bartlett-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsBannockburnIlDothtmlRoute =
  ShowerDoorsBannockburnIlDothtmlRouteImport.update({
    id: '/shower-doors-bannockburn-il.html',
    path: '/shower-doors-bannockburn-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorsArlingtonHeightsIlDothtmlRoute =
  ShowerDoorsArlingtonHeightsIlDothtmlRouteImport.update({
    id: '/shower-doors-arlington-heights-il.html',
    path: '/shower-doors-arlington-heights-il.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowerDoorBuyersGuideDothtmlRoute =
  ShowerDoorBuyersGuideDothtmlRouteImport.update({
    id: '/shower-door-buyers-guide.html',
    path: '/shower-door-buyers-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReplacementGlassDothtmlRoute = ReplacementGlassDothtmlRouteImport.update({
  id: '/replacement-glass.html',
  path: '/replacement-glass.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplacementGlassGuideDothtmlRoute =
  ReplacementGlassGuideDothtmlRouteImport.update({
    id: '/replacement-glass-guide.html',
    path: '/replacement-glass-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const RemodelingDothtmlRoute = RemodelingDothtmlRouteImport.update({
  id: '/remodeling.html',
  path: '/remodeling.html',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherCustomGlassDothtmlRoute = OtherCustomGlassDothtmlRouteImport.update({
  id: '/other-custom-glass.html',
  path: '/other-custom-glass.html',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherCustomGlassGuideDothtmlRoute =
  OtherCustomGlassGuideDothtmlRouteImport.update({
    id: '/other-custom-glass-guide.html',
    path: '/other-custom-glass-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfficePartitionsDothtmlRoute = OfficePartitionsDothtmlRouteImport.update({
  id: '/office-partitions.html',
  path: '/office-partitions.html',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficePartitionsGuideDothtmlRoute =
  OfficePartitionsGuideDothtmlRouteImport.update({
    id: '/office-partitions-guide.html',
    path: '/office-partitions-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const MirrorsDothtmlRoute = MirrorsDothtmlRouteImport.update({
  id: '/mirrors.html',
  path: '/mirrors.html',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorsBuyersGuideDothtmlRoute =
  MirrorsBuyersGuideDothtmlRouteImport.update({
    id: '/mirrors-buyers-guide.html',
    path: '/mirrors-buyers-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassRailingsDothtmlRoute = GlassRailingsDothtmlRouteImport.update({
  id: '/glass-railings.html',
  path: '/glass-railings.html',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassRailingsBuyersGuideDothtmlRoute =
  GlassRailingsBuyersGuideDothtmlRouteImport.update({
    id: '/glass-railings-buyers-guide.html',
    path: '/glass-railings-buyers-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const FramelessVsSemiFramelessShowerDoorsDothtmlRoute =
  FramelessVsSemiFramelessShowerDoorsDothtmlRouteImport.update({
    id: '/frameless-vs-semi-frameless-shower-doors.html',
    path: '/frameless-vs-semi-frameless-shower-doors.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomShowerGlassDothtmlRoute =
  CustomShowerGlassDothtmlRouteImport.update({
    id: '/custom-shower-glass.html',
    path: '/custom-shower-glass.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomShowerGlassGuideDothtmlRoute =
  CustomShowerGlassGuideDothtmlRouteImport.update({
    id: '/custom-shower-glass-guide.html',
    path: '/custom-shower-glass-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const BathroomRemodelGlassDothtmlRoute =
  BathroomRemodelGlassDothtmlRouteImport.update({
    id: '/bathroom-remodel-glass.html',
    path: '/bathroom-remodel-glass.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const BathroomRemodelGlassGuideDothtmlRoute =
  BathroomRemodelGlassGuideDothtmlRouteImport.update({
    id: '/bathroom-remodel-glass-guide.html',
    path: '/bathroom-remodel-glass-guide.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bathroom-remodel-glass-guide.html': typeof BathroomRemodelGlassGuideDothtmlRoute
  '/bathroom-remodel-glass.html': typeof BathroomRemodelGlassDothtmlRoute
  '/custom-shower-glass-guide.html': typeof CustomShowerGlassGuideDothtmlRoute
  '/custom-shower-glass.html': typeof CustomShowerGlassDothtmlRoute
  '/frameless-vs-semi-frameless-shower-doors.html': typeof FramelessVsSemiFramelessShowerDoorsDothtmlRoute
  '/glass-railings-buyers-guide.html': typeof GlassRailingsBuyersGuideDothtmlRoute
  '/glass-railings.html': typeof GlassRailingsDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/mirrors-buyers-guide.html': typeof MirrorsBuyersGuideDothtmlRoute
  '/mirrors.html': typeof MirrorsDothtmlRoute
  '/office-partitions-guide.html': typeof OfficePartitionsGuideDothtmlRoute
  '/office-partitions.html': typeof OfficePartitionsDothtmlRoute
  '/other-custom-glass-guide.html': typeof OtherCustomGlassGuideDothtmlRoute
  '/other-custom-glass.html': typeof OtherCustomGlassDothtmlRoute
  '/remodeling.html': typeof RemodelingDothtmlRoute
  '/replacement-glass-guide.html': typeof ReplacementGlassGuideDothtmlRoute
  '/replacement-glass.html': typeof ReplacementGlassDothtmlRoute
  '/shower-door-buyers-guide.html': typeof ShowerDoorBuyersGuideDothtmlRoute
  '/shower-doors-arlington-heights-il.html': typeof ShowerDoorsArlingtonHeightsIlDothtmlRoute
  '/shower-doors-bannockburn-il.html': typeof ShowerDoorsBannockburnIlDothtmlRoute
  '/shower-doors-bartlett-il.html': typeof ShowerDoorsBartlettIlDothtmlRoute
  '/shower-doors-buffalo-grove-il.html': typeof ShowerDoorsBuffaloGroveIlDothtmlRoute
  '/shower-doors-deerfield-il.html': typeof ShowerDoorsDeerfieldIlDothtmlRoute
  '/shower-doors-des-plaines-il.html': typeof ShowerDoorsDesPlainesIlDothtmlRoute
  '/shower-doors-elk-grove-village-il.html': typeof ShowerDoorsElkGroveVillageIlDothtmlRoute
  '/shower-doors-evanston-il.html': typeof ShowerDoorsEvanstonIlDothtmlRoute
  '/shower-doors-glencoe-il.html': typeof ShowerDoorsGlencoeIlDothtmlRoute
  '/shower-doors-glenview-il.html': typeof ShowerDoorsGlenviewIlDothtmlRoute
  '/shower-doors-hanover-park-il.html': typeof ShowerDoorsHanoverParkIlDothtmlRoute
  '/shower-doors-highland-park-il.html': typeof ShowerDoorsHighlandParkIlDothtmlRoute
  '/shower-doors-hoffman-estates-il.html': typeof ShowerDoorsHoffmanEstatesIlDothtmlRoute
  '/shower-doors-lake-forest-il.html': typeof ShowerDoorsLakeForestIlDothtmlRoute
  '/shower-doors-libertyville-il.html': typeof ShowerDoorsLibertyvilleIlDothtmlRoute
  '/shower-doors-lincolnshire-il.html': typeof ShowerDoorsLincolnshireIlDothtmlRoute
  '/shower-doors-mount-prospect-il.html': typeof ShowerDoorsMountProspectIlDothtmlRoute
  '/shower-doors-northbrook-il.html': typeof ShowerDoorsNorthbrookIlDothtmlRoute
  '/shower-doors-northfield-il.html': typeof ShowerDoorsNorthfieldIlDothtmlRoute
  '/shower-doors-palatine-il.html': typeof ShowerDoorsPalatineIlDothtmlRoute
  '/shower-doors-park-ridge-il.html': typeof ShowerDoorsParkRidgeIlDothtmlRoute
  '/shower-doors-riverwoods-il.html': typeof ShowerDoorsRiverwoodsIlDothtmlRoute
  '/shower-doors-rolling-meadows-il.html': typeof ShowerDoorsRollingMeadowsIlDothtmlRoute
  '/shower-doors-roselle-il.html': typeof ShowerDoorsRoselleIlDothtmlRoute
  '/shower-doors-skokie-il.html': typeof ShowerDoorsSkokieIlDothtmlRoute
  '/shower-doors-streamwood-il.html': typeof ShowerDoorsStreamwoodIlDothtmlRoute
  '/shower-doors-vernon-hills-il.html': typeof ShowerDoorsVernonHillsIlDothtmlRoute
  '/shower-doors-wheeling-il.html': typeof ShowerDoorsWheelingIlDothtmlRoute
  '/shower-doors-wilmette-il.html': typeof ShowerDoorsWilmetteIlDothtmlRoute
  '/shower-doors-winnetka-il.html': typeof ShowerDoorsWinnetkaIlDothtmlRoute
  '/shower-doors.html': typeof ShowerDoorsDothtmlRoute
  '/shower-enclosure-buyers-guide.html': typeof ShowerEnclosureBuyersGuideDothtmlRoute
  '/shower-enclosures.html': typeof ShowerEnclosuresDothtmlRoute
  '/tub-door-buyers-guide.html': typeof TubDoorBuyersGuideDothtmlRoute
  '/tub-doors.html': typeof TubDoorsDothtmlRoute
  '/wine-cigar-room-glass-guide.html': typeof WineCigarRoomGlassGuideDothtmlRoute
  '/wine-cigar-rooms.html': typeof WineCigarRoomsDothtmlRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bathroom-remodel-glass-guide.html': typeof BathroomRemodelGlassGuideDothtmlRoute
  '/bathroom-remodel-glass.html': typeof BathroomRemodelGlassDothtmlRoute
  '/custom-shower-glass-guide.html': typeof CustomShowerGlassGuideDothtmlRoute
  '/custom-shower-glass.html': typeof CustomShowerGlassDothtmlRoute
  '/frameless-vs-semi-frameless-shower-doors.html': typeof FramelessVsSemiFramelessShowerDoorsDothtmlRoute
  '/glass-railings-buyers-guide.html': typeof GlassRailingsBuyersGuideDothtmlRoute
  '/glass-railings.html': typeof GlassRailingsDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/mirrors-buyers-guide.html': typeof MirrorsBuyersGuideDothtmlRoute
  '/mirrors.html': typeof MirrorsDothtmlRoute
  '/office-partitions-guide.html': typeof OfficePartitionsGuideDothtmlRoute
  '/office-partitions.html': typeof OfficePartitionsDothtmlRoute
  '/other-custom-glass-guide.html': typeof OtherCustomGlassGuideDothtmlRoute
  '/other-custom-glass.html': typeof OtherCustomGlassDothtmlRoute
  '/remodeling.html': typeof RemodelingDothtmlRoute
  '/replacement-glass-guide.html': typeof ReplacementGlassGuideDothtmlRoute
  '/replacement-glass.html': typeof ReplacementGlassDothtmlRoute
  '/shower-door-buyers-guide.html': typeof ShowerDoorBuyersGuideDothtmlRoute
  '/shower-doors-arlington-heights-il.html': typeof ShowerDoorsArlingtonHeightsIlDothtmlRoute
  '/shower-doors-bannockburn-il.html': typeof ShowerDoorsBannockburnIlDothtmlRoute
  '/shower-doors-bartlett-il.html': typeof ShowerDoorsBartlettIlDothtmlRoute
  '/shower-doors-buffalo-grove-il.html': typeof ShowerDoorsBuffaloGroveIlDothtmlRoute
  '/shower-doors-deerfield-il.html': typeof ShowerDoorsDeerfieldIlDothtmlRoute
  '/shower-doors-des-plaines-il.html': typeof ShowerDoorsDesPlainesIlDothtmlRoute
  '/shower-doors-elk-grove-village-il.html': typeof ShowerDoorsElkGroveVillageIlDothtmlRoute
  '/shower-doors-evanston-il.html': typeof ShowerDoorsEvanstonIlDothtmlRoute
  '/shower-doors-glencoe-il.html': typeof ShowerDoorsGlencoeIlDothtmlRoute
  '/shower-doors-glenview-il.html': typeof ShowerDoorsGlenviewIlDothtmlRoute
  '/shower-doors-hanover-park-il.html': typeof ShowerDoorsHanoverParkIlDothtmlRoute
  '/shower-doors-highland-park-il.html': typeof ShowerDoorsHighlandParkIlDothtmlRoute
  '/shower-doors-hoffman-estates-il.html': typeof ShowerDoorsHoffmanEstatesIlDothtmlRoute
  '/shower-doors-lake-forest-il.html': typeof ShowerDoorsLakeForestIlDothtmlRoute
  '/shower-doors-libertyville-il.html': typeof ShowerDoorsLibertyvilleIlDothtmlRoute
  '/shower-doors-lincolnshire-il.html': typeof ShowerDoorsLincolnshireIlDothtmlRoute
  '/shower-doors-mount-prospect-il.html': typeof ShowerDoorsMountProspectIlDothtmlRoute
  '/shower-doors-northbrook-il.html': typeof ShowerDoorsNorthbrookIlDothtmlRoute
  '/shower-doors-northfield-il.html': typeof ShowerDoorsNorthfieldIlDothtmlRoute
  '/shower-doors-palatine-il.html': typeof ShowerDoorsPalatineIlDothtmlRoute
  '/shower-doors-park-ridge-il.html': typeof ShowerDoorsParkRidgeIlDothtmlRoute
  '/shower-doors-riverwoods-il.html': typeof ShowerDoorsRiverwoodsIlDothtmlRoute
  '/shower-doors-rolling-meadows-il.html': typeof ShowerDoorsRollingMeadowsIlDothtmlRoute
  '/shower-doors-roselle-il.html': typeof ShowerDoorsRoselleIlDothtmlRoute
  '/shower-doors-skokie-il.html': typeof ShowerDoorsSkokieIlDothtmlRoute
  '/shower-doors-streamwood-il.html': typeof ShowerDoorsStreamwoodIlDothtmlRoute
  '/shower-doors-vernon-hills-il.html': typeof ShowerDoorsVernonHillsIlDothtmlRoute
  '/shower-doors-wheeling-il.html': typeof ShowerDoorsWheelingIlDothtmlRoute
  '/shower-doors-wilmette-il.html': typeof ShowerDoorsWilmetteIlDothtmlRoute
  '/shower-doors-winnetka-il.html': typeof ShowerDoorsWinnetkaIlDothtmlRoute
  '/shower-doors.html': typeof ShowerDoorsDothtmlRoute
  '/shower-enclosure-buyers-guide.html': typeof ShowerEnclosureBuyersGuideDothtmlRoute
  '/shower-enclosures.html': typeof ShowerEnclosuresDothtmlRoute
  '/tub-door-buyers-guide.html': typeof TubDoorBuyersGuideDothtmlRoute
  '/tub-doors.html': typeof TubDoorsDothtmlRoute
  '/wine-cigar-room-glass-guide.html': typeof WineCigarRoomGlassGuideDothtmlRoute
  '/wine-cigar-rooms.html': typeof WineCigarRoomsDothtmlRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bathroom-remodel-glass-guide.html': typeof BathroomRemodelGlassGuideDothtmlRoute
  '/bathroom-remodel-glass.html': typeof BathroomRemodelGlassDothtmlRoute
  '/custom-shower-glass-guide.html': typeof CustomShowerGlassGuideDothtmlRoute
  '/custom-shower-glass.html': typeof CustomShowerGlassDothtmlRoute
  '/frameless-vs-semi-frameless-shower-doors.html': typeof FramelessVsSemiFramelessShowerDoorsDothtmlRoute
  '/glass-railings-buyers-guide.html': typeof GlassRailingsBuyersGuideDothtmlRoute
  '/glass-railings.html': typeof GlassRailingsDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/mirrors-buyers-guide.html': typeof MirrorsBuyersGuideDothtmlRoute
  '/mirrors.html': typeof MirrorsDothtmlRoute
  '/office-partitions-guide.html': typeof OfficePartitionsGuideDothtmlRoute
  '/office-partitions.html': typeof OfficePartitionsDothtmlRoute
  '/other-custom-glass-guide.html': typeof OtherCustomGlassGuideDothtmlRoute
  '/other-custom-glass.html': typeof OtherCustomGlassDothtmlRoute
  '/remodeling.html': typeof RemodelingDothtmlRoute
  '/replacement-glass-guide.html': typeof ReplacementGlassGuideDothtmlRoute
  '/replacement-glass.html': typeof ReplacementGlassDothtmlRoute
  '/shower-door-buyers-guide.html': typeof ShowerDoorBuyersGuideDothtmlRoute
  '/shower-doors-arlington-heights-il.html': typeof ShowerDoorsArlingtonHeightsIlDothtmlRoute
  '/shower-doors-bannockburn-il.html': typeof ShowerDoorsBannockburnIlDothtmlRoute
  '/shower-doors-bartlett-il.html': typeof ShowerDoorsBartlettIlDothtmlRoute
  '/shower-doors-buffalo-grove-il.html': typeof ShowerDoorsBuffaloGroveIlDothtmlRoute
  '/shower-doors-deerfield-il.html': typeof ShowerDoorsDeerfieldIlDothtmlRoute
  '/shower-doors-des-plaines-il.html': typeof ShowerDoorsDesPlainesIlDothtmlRoute
  '/shower-doors-elk-grove-village-il.html': typeof ShowerDoorsElkGroveVillageIlDothtmlRoute
  '/shower-doors-evanston-il.html': typeof ShowerDoorsEvanstonIlDothtmlRoute
  '/shower-doors-glencoe-il.html': typeof ShowerDoorsGlencoeIlDothtmlRoute
  '/shower-doors-glenview-il.html': typeof ShowerDoorsGlenviewIlDothtmlRoute
  '/shower-doors-hanover-park-il.html': typeof ShowerDoorsHanoverParkIlDothtmlRoute
  '/shower-doors-highland-park-il.html': typeof ShowerDoorsHighlandParkIlDothtmlRoute
  '/shower-doors-hoffman-estates-il.html': typeof ShowerDoorsHoffmanEstatesIlDothtmlRoute
  '/shower-doors-lake-forest-il.html': typeof ShowerDoorsLakeForestIlDothtmlRoute
  '/shower-doors-libertyville-il.html': typeof ShowerDoorsLibertyvilleIlDothtmlRoute
  '/shower-doors-lincolnshire-il.html': typeof ShowerDoorsLincolnshireIlDothtmlRoute
  '/shower-doors-mount-prospect-il.html': typeof ShowerDoorsMountProspectIlDothtmlRoute
  '/shower-doors-northbrook-il.html': typeof ShowerDoorsNorthbrookIlDothtmlRoute
  '/shower-doors-northfield-il.html': typeof ShowerDoorsNorthfieldIlDothtmlRoute
  '/shower-doors-palatine-il.html': typeof ShowerDoorsPalatineIlDothtmlRoute
  '/shower-doors-park-ridge-il.html': typeof ShowerDoorsParkRidgeIlDothtmlRoute
  '/shower-doors-riverwoods-il.html': typeof ShowerDoorsRiverwoodsIlDothtmlRoute
  '/shower-doors-rolling-meadows-il.html': typeof ShowerDoorsRollingMeadowsIlDothtmlRoute
  '/shower-doors-roselle-il.html': typeof ShowerDoorsRoselleIlDothtmlRoute
  '/shower-doors-skokie-il.html': typeof ShowerDoorsSkokieIlDothtmlRoute
  '/shower-doors-streamwood-il.html': typeof ShowerDoorsStreamwoodIlDothtmlRoute
  '/shower-doors-vernon-hills-il.html': typeof ShowerDoorsVernonHillsIlDothtmlRoute
  '/shower-doors-wheeling-il.html': typeof ShowerDoorsWheelingIlDothtmlRoute
  '/shower-doors-wilmette-il.html': typeof ShowerDoorsWilmetteIlDothtmlRoute
  '/shower-doors-winnetka-il.html': typeof ShowerDoorsWinnetkaIlDothtmlRoute
  '/shower-doors.html': typeof ShowerDoorsDothtmlRoute
  '/shower-enclosure-buyers-guide.html': typeof ShowerEnclosureBuyersGuideDothtmlRoute
  '/shower-enclosures.html': typeof ShowerEnclosuresDothtmlRoute
  '/tub-door-buyers-guide.html': typeof TubDoorBuyersGuideDothtmlRoute
  '/tub-doors.html': typeof TubDoorsDothtmlRoute
  '/wine-cigar-room-glass-guide.html': typeof WineCigarRoomGlassGuideDothtmlRoute
  '/wine-cigar-rooms.html': typeof WineCigarRoomsDothtmlRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bathroom-remodel-glass-guide.html'
    | '/bathroom-remodel-glass.html'
    | '/custom-shower-glass-guide.html'
    | '/custom-shower-glass.html'
    | '/frameless-vs-semi-frameless-shower-doors.html'
    | '/glass-railings-buyers-guide.html'
    | '/glass-railings.html'
    | '/index.html'
    | '/mirrors-buyers-guide.html'
    | '/mirrors.html'
    | '/office-partitions-guide.html'
    | '/office-partitions.html'
    | '/other-custom-glass-guide.html'
    | '/other-custom-glass.html'
    | '/remodeling.html'
    | '/replacement-glass-guide.html'
    | '/replacement-glass.html'
    | '/shower-door-buyers-guide.html'
    | '/shower-doors-arlington-heights-il.html'
    | '/shower-doors-bannockburn-il.html'
    | '/shower-doors-bartlett-il.html'
    | '/shower-doors-buffalo-grove-il.html'
    | '/shower-doors-deerfield-il.html'
    | '/shower-doors-des-plaines-il.html'
    | '/shower-doors-elk-grove-village-il.html'
    | '/shower-doors-evanston-il.html'
    | '/shower-doors-glencoe-il.html'
    | '/shower-doors-glenview-il.html'
    | '/shower-doors-hanover-park-il.html'
    | '/shower-doors-highland-park-il.html'
    | '/shower-doors-hoffman-estates-il.html'
    | '/shower-doors-lake-forest-il.html'
    | '/shower-doors-libertyville-il.html'
    | '/shower-doors-lincolnshire-il.html'
    | '/shower-doors-mount-prospect-il.html'
    | '/shower-doors-northbrook-il.html'
    | '/shower-doors-northfield-il.html'
    | '/shower-doors-palatine-il.html'
    | '/shower-doors-park-ridge-il.html'
    | '/shower-doors-riverwoods-il.html'
    | '/shower-doors-rolling-meadows-il.html'
    | '/shower-doors-roselle-il.html'
    | '/shower-doors-skokie-il.html'
    | '/shower-doors-streamwood-il.html'
    | '/shower-doors-vernon-hills-il.html'
    | '/shower-doors-wheeling-il.html'
    | '/shower-doors-wilmette-il.html'
    | '/shower-doors-winnetka-il.html'
    | '/shower-doors.html'
    | '/shower-enclosure-buyers-guide.html'
    | '/shower-enclosures.html'
    | '/tub-door-buyers-guide.html'
    | '/tub-doors.html'
    | '/wine-cigar-room-glass-guide.html'
    | '/wine-cigar-rooms.html'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bathroom-remodel-glass-guide.html'
    | '/bathroom-remodel-glass.html'
    | '/custom-shower-glass-guide.html'
    | '/custom-shower-glass.html'
    | '/frameless-vs-semi-frameless-shower-doors.html'
    | '/glass-railings-buyers-guide.html'
    | '/glass-railings.html'
    | '/index.html'
    | '/mirrors-buyers-guide.html'
    | '/mirrors.html'
    | '/office-partitions-guide.html'
    | '/office-partitions.html'
    | '/other-custom-glass-guide.html'
    | '/other-custom-glass.html'
    | '/remodeling.html'
    | '/replacement-glass-guide.html'
    | '/replacement-glass.html'
    | '/shower-door-buyers-guide.html'
    | '/shower-doors-arlington-heights-il.html'
    | '/shower-doors-bannockburn-il.html'
    | '/shower-doors-bartlett-il.html'
    | '/shower-doors-buffalo-grove-il.html'
    | '/shower-doors-deerfield-il.html'
    | '/shower-doors-des-plaines-il.html'
    | '/shower-doors-elk-grove-village-il.html'
    | '/shower-doors-evanston-il.html'
    | '/shower-doors-glencoe-il.html'
    | '/shower-doors-glenview-il.html'
    | '/shower-doors-hanover-park-il.html'
    | '/shower-doors-highland-park-il.html'
    | '/shower-doors-hoffman-estates-il.html'
    | '/shower-doors-lake-forest-il.html'
    | '/shower-doors-libertyville-il.html'
    | '/shower-doors-lincolnshire-il.html'
    | '/shower-doors-mount-prospect-il.html'
    | '/shower-doors-northbrook-il.html'
    | '/shower-doors-northfield-il.html'
    | '/shower-doors-palatine-il.html'
    | '/shower-doors-park-ridge-il.html'
    | '/shower-doors-riverwoods-il.html'
    | '/shower-doors-rolling-meadows-il.html'
    | '/shower-doors-roselle-il.html'
    | '/shower-doors-skokie-il.html'
    | '/shower-doors-streamwood-il.html'
    | '/shower-doors-vernon-hills-il.html'
    | '/shower-doors-wheeling-il.html'
    | '/shower-doors-wilmette-il.html'
    | '/shower-doors-winnetka-il.html'
    | '/shower-doors.html'
    | '/shower-enclosure-buyers-guide.html'
    | '/shower-enclosures.html'
    | '/tub-door-buyers-guide.html'
    | '/tub-doors.html'
    | '/wine-cigar-room-glass-guide.html'
    | '/wine-cigar-rooms.html'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/bathroom-remodel-glass-guide.html'
    | '/bathroom-remodel-glass.html'
    | '/custom-shower-glass-guide.html'
    | '/custom-shower-glass.html'
    | '/frameless-vs-semi-frameless-shower-doors.html'
    | '/glass-railings-buyers-guide.html'
    | '/glass-railings.html'
    | '/index.html'
    | '/mirrors-buyers-guide.html'
    | '/mirrors.html'
    | '/office-partitions-guide.html'
    | '/office-partitions.html'
    | '/other-custom-glass-guide.html'
    | '/other-custom-glass.html'
    | '/remodeling.html'
    | '/replacement-glass-guide.html'
    | '/replacement-glass.html'
    | '/shower-door-buyers-guide.html'
    | '/shower-doors-arlington-heights-il.html'
    | '/shower-doors-bannockburn-il.html'
    | '/shower-doors-bartlett-il.html'
    | '/shower-doors-buffalo-grove-il.html'
    | '/shower-doors-deerfield-il.html'
    | '/shower-doors-des-plaines-il.html'
    | '/shower-doors-elk-grove-village-il.html'
    | '/shower-doors-evanston-il.html'
    | '/shower-doors-glencoe-il.html'
    | '/shower-doors-glenview-il.html'
    | '/shower-doors-hanover-park-il.html'
    | '/shower-doors-highland-park-il.html'
    | '/shower-doors-hoffman-estates-il.html'
    | '/shower-doors-lake-forest-il.html'
    | '/shower-doors-libertyville-il.html'
    | '/shower-doors-lincolnshire-il.html'
    | '/shower-doors-mount-prospect-il.html'
    | '/shower-doors-northbrook-il.html'
    | '/shower-doors-northfield-il.html'
    | '/shower-doors-palatine-il.html'
    | '/shower-doors-park-ridge-il.html'
    | '/shower-doors-riverwoods-il.html'
    | '/shower-doors-rolling-meadows-il.html'
    | '/shower-doors-roselle-il.html'
    | '/shower-doors-skokie-il.html'
    | '/shower-doors-streamwood-il.html'
    | '/shower-doors-vernon-hills-il.html'
    | '/shower-doors-wheeling-il.html'
    | '/shower-doors-wilmette-il.html'
    | '/shower-doors-winnetka-il.html'
    | '/shower-doors.html'
    | '/shower-enclosure-buyers-guide.html'
    | '/shower-enclosures.html'
    | '/tub-door-buyers-guide.html'
    | '/tub-doors.html'
    | '/wine-cigar-room-glass-guide.html'
    | '/wine-cigar-rooms.html'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BathroomRemodelGlassGuideDothtmlRoute: typeof BathroomRemodelGlassGuideDothtmlRoute
  BathroomRemodelGlassDothtmlRoute: typeof BathroomRemodelGlassDothtmlRoute
  CustomShowerGlassGuideDothtmlRoute: typeof CustomShowerGlassGuideDothtmlRoute
  CustomShowerGlassDothtmlRoute: typeof CustomShowerGlassDothtmlRoute
  FramelessVsSemiFramelessShowerDoorsDothtmlRoute: typeof FramelessVsSemiFramelessShowerDoorsDothtmlRoute
  GlassRailingsBuyersGuideDothtmlRoute: typeof GlassRailingsBuyersGuideDothtmlRoute
  GlassRailingsDothtmlRoute: typeof GlassRailingsDothtmlRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  MirrorsBuyersGuideDothtmlRoute: typeof MirrorsBuyersGuideDothtmlRoute
  MirrorsDothtmlRoute: typeof MirrorsDothtmlRoute
  OfficePartitionsGuideDothtmlRoute: typeof OfficePartitionsGuideDothtmlRoute
  OfficePartitionsDothtmlRoute: typeof OfficePartitionsDothtmlRoute
  OtherCustomGlassGuideDothtmlRoute: typeof OtherCustomGlassGuideDothtmlRoute
  OtherCustomGlassDothtmlRoute: typeof OtherCustomGlassDothtmlRoute
  RemodelingDothtmlRoute: typeof RemodelingDothtmlRoute
  ReplacementGlassGuideDothtmlRoute: typeof ReplacementGlassGuideDothtmlRoute
  ReplacementGlassDothtmlRoute: typeof ReplacementGlassDothtmlRoute
  ShowerDoorBuyersGuideDothtmlRoute: typeof ShowerDoorBuyersGuideDothtmlRoute
  ShowerDoorsArlingtonHeightsIlDothtmlRoute: typeof ShowerDoorsArlingtonHeightsIlDothtmlRoute
  ShowerDoorsBannockburnIlDothtmlRoute: typeof ShowerDoorsBannockburnIlDothtmlRoute
  ShowerDoorsBartlettIlDothtmlRoute: typeof ShowerDoorsBartlettIlDothtmlRoute
  ShowerDoorsBuffaloGroveIlDothtmlRoute: typeof ShowerDoorsBuffaloGroveIlDothtmlRoute
  ShowerDoorsDeerfieldIlDothtmlRoute: typeof ShowerDoorsDeerfieldIlDothtmlRoute
  ShowerDoorsDesPlainesIlDothtmlRoute: typeof ShowerDoorsDesPlainesIlDothtmlRoute
  ShowerDoorsElkGroveVillageIlDothtmlRoute: typeof ShowerDoorsElkGroveVillageIlDothtmlRoute
  ShowerDoorsEvanstonIlDothtmlRoute: typeof ShowerDoorsEvanstonIlDothtmlRoute
  ShowerDoorsGlencoeIlDothtmlRoute: typeof ShowerDoorsGlencoeIlDothtmlRoute
  ShowerDoorsGlenviewIlDothtmlRoute: typeof ShowerDoorsGlenviewIlDothtmlRoute
  ShowerDoorsHanoverParkIlDothtmlRoute: typeof ShowerDoorsHanoverParkIlDothtmlRoute
  ShowerDoorsHighlandParkIlDothtmlRoute: typeof ShowerDoorsHighlandParkIlDothtmlRoute
  ShowerDoorsHoffmanEstatesIlDothtmlRoute: typeof ShowerDoorsHoffmanEstatesIlDothtmlRoute
  ShowerDoorsLakeForestIlDothtmlRoute: typeof ShowerDoorsLakeForestIlDothtmlRoute
  ShowerDoorsLibertyvilleIlDothtmlRoute: typeof ShowerDoorsLibertyvilleIlDothtmlRoute
  ShowerDoorsLincolnshireIlDothtmlRoute: typeof ShowerDoorsLincolnshireIlDothtmlRoute
  ShowerDoorsMountProspectIlDothtmlRoute: typeof ShowerDoorsMountProspectIlDothtmlRoute
  ShowerDoorsNorthbrookIlDothtmlRoute: typeof ShowerDoorsNorthbrookIlDothtmlRoute
  ShowerDoorsNorthfieldIlDothtmlRoute: typeof ShowerDoorsNorthfieldIlDothtmlRoute
  ShowerDoorsPalatineIlDothtmlRoute: typeof ShowerDoorsPalatineIlDothtmlRoute
  ShowerDoorsParkRidgeIlDothtmlRoute: typeof ShowerDoorsParkRidgeIlDothtmlRoute
  ShowerDoorsRiverwoodsIlDothtmlRoute: typeof ShowerDoorsRiverwoodsIlDothtmlRoute
  ShowerDoorsRollingMeadowsIlDothtmlRoute: typeof ShowerDoorsRollingMeadowsIlDothtmlRoute
  ShowerDoorsRoselleIlDothtmlRoute: typeof ShowerDoorsRoselleIlDothtmlRoute
  ShowerDoorsSkokieIlDothtmlRoute: typeof ShowerDoorsSkokieIlDothtmlRoute
  ShowerDoorsStreamwoodIlDothtmlRoute: typeof ShowerDoorsStreamwoodIlDothtmlRoute
  ShowerDoorsVernonHillsIlDothtmlRoute: typeof ShowerDoorsVernonHillsIlDothtmlRoute
  ShowerDoorsWheelingIlDothtmlRoute: typeof ShowerDoorsWheelingIlDothtmlRoute
  ShowerDoorsWilmetteIlDothtmlRoute: typeof ShowerDoorsWilmetteIlDothtmlRoute
  ShowerDoorsWinnetkaIlDothtmlRoute: typeof ShowerDoorsWinnetkaIlDothtmlRoute
  ShowerDoorsDothtmlRoute: typeof ShowerDoorsDothtmlRoute
  ShowerEnclosureBuyersGuideDothtmlRoute: typeof ShowerEnclosureBuyersGuideDothtmlRoute
  ShowerEnclosuresDothtmlRoute: typeof ShowerEnclosuresDothtmlRoute
  TubDoorBuyersGuideDothtmlRoute: typeof TubDoorBuyersGuideDothtmlRoute
  TubDoorsDothtmlRoute: typeof TubDoorsDothtmlRoute
  WineCigarRoomGlassGuideDothtmlRoute: typeof WineCigarRoomGlassGuideDothtmlRoute
  WineCigarRoomsDothtmlRoute: typeof WineCigarRoomsDothtmlRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wine-cigar-rooms.html': {
      id: '/wine-cigar-rooms.html'
      path: '/wine-cigar-rooms.html'
      fullPath: '/wine-cigar-rooms.html'
      preLoaderRoute: typeof WineCigarRoomsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wine-cigar-room-glass-guide.html': {
      id: '/wine-cigar-room-glass-guide.html'
      path: '/wine-cigar-room-glass-guide.html'
      fullPath: '/wine-cigar-room-glass-guide.html'
      preLoaderRoute: typeof WineCigarRoomGlassGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tub-doors.html': {
      id: '/tub-doors.html'
      path: '/tub-doors.html'
      fullPath: '/tub-doors.html'
      preLoaderRoute: typeof TubDoorsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tub-door-buyers-guide.html': {
      id: '/tub-door-buyers-guide.html'
      path: '/tub-door-buyers-guide.html'
      fullPath: '/tub-door-buyers-guide.html'
      preLoaderRoute: typeof TubDoorBuyersGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-enclosures.html': {
      id: '/shower-enclosures.html'
      path: '/shower-enclosures.html'
      fullPath: '/shower-enclosures.html'
      preLoaderRoute: typeof ShowerEnclosuresDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-enclosure-buyers-guide.html': {
      id: '/shower-enclosure-buyers-guide.html'
      path: '/shower-enclosure-buyers-guide.html'
      fullPath: '/shower-enclosure-buyers-guide.html'
      preLoaderRoute: typeof ShowerEnclosureBuyersGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors.html': {
      id: '/shower-doors.html'
      path: '/shower-doors.html'
      fullPath: '/shower-doors.html'
      preLoaderRoute: typeof ShowerDoorsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-winnetka-il.html': {
      id: '/shower-doors-winnetka-il.html'
      path: '/shower-doors-winnetka-il.html'
      fullPath: '/shower-doors-winnetka-il.html'
      preLoaderRoute: typeof ShowerDoorsWinnetkaIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-wilmette-il.html': {
      id: '/shower-doors-wilmette-il.html'
      path: '/shower-doors-wilmette-il.html'
      fullPath: '/shower-doors-wilmette-il.html'
      preLoaderRoute: typeof ShowerDoorsWilmetteIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-wheeling-il.html': {
      id: '/shower-doors-wheeling-il.html'
      path: '/shower-doors-wheeling-il.html'
      fullPath: '/shower-doors-wheeling-il.html'
      preLoaderRoute: typeof ShowerDoorsWheelingIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-vernon-hills-il.html': {
      id: '/shower-doors-vernon-hills-il.html'
      path: '/shower-doors-vernon-hills-il.html'
      fullPath: '/shower-doors-vernon-hills-il.html'
      preLoaderRoute: typeof ShowerDoorsVernonHillsIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-streamwood-il.html': {
      id: '/shower-doors-streamwood-il.html'
      path: '/shower-doors-streamwood-il.html'
      fullPath: '/shower-doors-streamwood-il.html'
      preLoaderRoute: typeof ShowerDoorsStreamwoodIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-skokie-il.html': {
      id: '/shower-doors-skokie-il.html'
      path: '/shower-doors-skokie-il.html'
      fullPath: '/shower-doors-skokie-il.html'
      preLoaderRoute: typeof ShowerDoorsSkokieIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-roselle-il.html': {
      id: '/shower-doors-roselle-il.html'
      path: '/shower-doors-roselle-il.html'
      fullPath: '/shower-doors-roselle-il.html'
      preLoaderRoute: typeof ShowerDoorsRoselleIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-rolling-meadows-il.html': {
      id: '/shower-doors-rolling-meadows-il.html'
      path: '/shower-doors-rolling-meadows-il.html'
      fullPath: '/shower-doors-rolling-meadows-il.html'
      preLoaderRoute: typeof ShowerDoorsRollingMeadowsIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-riverwoods-il.html': {
      id: '/shower-doors-riverwoods-il.html'
      path: '/shower-doors-riverwoods-il.html'
      fullPath: '/shower-doors-riverwoods-il.html'
      preLoaderRoute: typeof ShowerDoorsRiverwoodsIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-park-ridge-il.html': {
      id: '/shower-doors-park-ridge-il.html'
      path: '/shower-doors-park-ridge-il.html'
      fullPath: '/shower-doors-park-ridge-il.html'
      preLoaderRoute: typeof ShowerDoorsParkRidgeIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-palatine-il.html': {
      id: '/shower-doors-palatine-il.html'
      path: '/shower-doors-palatine-il.html'
      fullPath: '/shower-doors-palatine-il.html'
      preLoaderRoute: typeof ShowerDoorsPalatineIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-northfield-il.html': {
      id: '/shower-doors-northfield-il.html'
      path: '/shower-doors-northfield-il.html'
      fullPath: '/shower-doors-northfield-il.html'
      preLoaderRoute: typeof ShowerDoorsNorthfieldIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-northbrook-il.html': {
      id: '/shower-doors-northbrook-il.html'
      path: '/shower-doors-northbrook-il.html'
      fullPath: '/shower-doors-northbrook-il.html'
      preLoaderRoute: typeof ShowerDoorsNorthbrookIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-mount-prospect-il.html': {
      id: '/shower-doors-mount-prospect-il.html'
      path: '/shower-doors-mount-prospect-il.html'
      fullPath: '/shower-doors-mount-prospect-il.html'
      preLoaderRoute: typeof ShowerDoorsMountProspectIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-lincolnshire-il.html': {
      id: '/shower-doors-lincolnshire-il.html'
      path: '/shower-doors-lincolnshire-il.html'
      fullPath: '/shower-doors-lincolnshire-il.html'
      preLoaderRoute: typeof ShowerDoorsLincolnshireIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-libertyville-il.html': {
      id: '/shower-doors-libertyville-il.html'
      path: '/shower-doors-libertyville-il.html'
      fullPath: '/shower-doors-libertyville-il.html'
      preLoaderRoute: typeof ShowerDoorsLibertyvilleIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-lake-forest-il.html': {
      id: '/shower-doors-lake-forest-il.html'
      path: '/shower-doors-lake-forest-il.html'
      fullPath: '/shower-doors-lake-forest-il.html'
      preLoaderRoute: typeof ShowerDoorsLakeForestIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-hoffman-estates-il.html': {
      id: '/shower-doors-hoffman-estates-il.html'
      path: '/shower-doors-hoffman-estates-il.html'
      fullPath: '/shower-doors-hoffman-estates-il.html'
      preLoaderRoute: typeof ShowerDoorsHoffmanEstatesIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-highland-park-il.html': {
      id: '/shower-doors-highland-park-il.html'
      path: '/shower-doors-highland-park-il.html'
      fullPath: '/shower-doors-highland-park-il.html'
      preLoaderRoute: typeof ShowerDoorsHighlandParkIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-hanover-park-il.html': {
      id: '/shower-doors-hanover-park-il.html'
      path: '/shower-doors-hanover-park-il.html'
      fullPath: '/shower-doors-hanover-park-il.html'
      preLoaderRoute: typeof ShowerDoorsHanoverParkIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-glenview-il.html': {
      id: '/shower-doors-glenview-il.html'
      path: '/shower-doors-glenview-il.html'
      fullPath: '/shower-doors-glenview-il.html'
      preLoaderRoute: typeof ShowerDoorsGlenviewIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-glencoe-il.html': {
      id: '/shower-doors-glencoe-il.html'
      path: '/shower-doors-glencoe-il.html'
      fullPath: '/shower-doors-glencoe-il.html'
      preLoaderRoute: typeof ShowerDoorsGlencoeIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-evanston-il.html': {
      id: '/shower-doors-evanston-il.html'
      path: '/shower-doors-evanston-il.html'
      fullPath: '/shower-doors-evanston-il.html'
      preLoaderRoute: typeof ShowerDoorsEvanstonIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-elk-grove-village-il.html': {
      id: '/shower-doors-elk-grove-village-il.html'
      path: '/shower-doors-elk-grove-village-il.html'
      fullPath: '/shower-doors-elk-grove-village-il.html'
      preLoaderRoute: typeof ShowerDoorsElkGroveVillageIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-des-plaines-il.html': {
      id: '/shower-doors-des-plaines-il.html'
      path: '/shower-doors-des-plaines-il.html'
      fullPath: '/shower-doors-des-plaines-il.html'
      preLoaderRoute: typeof ShowerDoorsDesPlainesIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-deerfield-il.html': {
      id: '/shower-doors-deerfield-il.html'
      path: '/shower-doors-deerfield-il.html'
      fullPath: '/shower-doors-deerfield-il.html'
      preLoaderRoute: typeof ShowerDoorsDeerfieldIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-buffalo-grove-il.html': {
      id: '/shower-doors-buffalo-grove-il.html'
      path: '/shower-doors-buffalo-grove-il.html'
      fullPath: '/shower-doors-buffalo-grove-il.html'
      preLoaderRoute: typeof ShowerDoorsBuffaloGroveIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-bartlett-il.html': {
      id: '/shower-doors-bartlett-il.html'
      path: '/shower-doors-bartlett-il.html'
      fullPath: '/shower-doors-bartlett-il.html'
      preLoaderRoute: typeof ShowerDoorsBartlettIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-bannockburn-il.html': {
      id: '/shower-doors-bannockburn-il.html'
      path: '/shower-doors-bannockburn-il.html'
      fullPath: '/shower-doors-bannockburn-il.html'
      preLoaderRoute: typeof ShowerDoorsBannockburnIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-doors-arlington-heights-il.html': {
      id: '/shower-doors-arlington-heights-il.html'
      path: '/shower-doors-arlington-heights-il.html'
      fullPath: '/shower-doors-arlington-heights-il.html'
      preLoaderRoute: typeof ShowerDoorsArlingtonHeightsIlDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower-door-buyers-guide.html': {
      id: '/shower-door-buyers-guide.html'
      path: '/shower-door-buyers-guide.html'
      fullPath: '/shower-door-buyers-guide.html'
      preLoaderRoute: typeof ShowerDoorBuyersGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replacement-glass.html': {
      id: '/replacement-glass.html'
      path: '/replacement-glass.html'
      fullPath: '/replacement-glass.html'
      preLoaderRoute: typeof ReplacementGlassDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replacement-glass-guide.html': {
      id: '/replacement-glass-guide.html'
      path: '/replacement-glass-guide.html'
      fullPath: '/replacement-glass-guide.html'
      preLoaderRoute: typeof ReplacementGlassGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remodeling.html': {
      id: '/remodeling.html'
      path: '/remodeling.html'
      fullPath: '/remodeling.html'
      preLoaderRoute: typeof RemodelingDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-custom-glass.html': {
      id: '/other-custom-glass.html'
      path: '/other-custom-glass.html'
      fullPath: '/other-custom-glass.html'
      preLoaderRoute: typeof OtherCustomGlassDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-custom-glass-guide.html': {
      id: '/other-custom-glass-guide.html'
      path: '/other-custom-glass-guide.html'
      fullPath: '/other-custom-glass-guide.html'
      preLoaderRoute: typeof OtherCustomGlassGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-partitions.html': {
      id: '/office-partitions.html'
      path: '/office-partitions.html'
      fullPath: '/office-partitions.html'
      preLoaderRoute: typeof OfficePartitionsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-partitions-guide.html': {
      id: '/office-partitions-guide.html'
      path: '/office-partitions-guide.html'
      fullPath: '/office-partitions-guide.html'
      preLoaderRoute: typeof OfficePartitionsGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirrors.html': {
      id: '/mirrors.html'
      path: '/mirrors.html'
      fullPath: '/mirrors.html'
      preLoaderRoute: typeof MirrorsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirrors-buyers-guide.html': {
      id: '/mirrors-buyers-guide.html'
      path: '/mirrors-buyers-guide.html'
      fullPath: '/mirrors-buyers-guide.html'
      preLoaderRoute: typeof MirrorsBuyersGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass-railings.html': {
      id: '/glass-railings.html'
      path: '/glass-railings.html'
      fullPath: '/glass-railings.html'
      preLoaderRoute: typeof GlassRailingsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glass-railings-buyers-guide.html': {
      id: '/glass-railings-buyers-guide.html'
      path: '/glass-railings-buyers-guide.html'
      fullPath: '/glass-railings-buyers-guide.html'
      preLoaderRoute: typeof GlassRailingsBuyersGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameless-vs-semi-frameless-shower-doors.html': {
      id: '/frameless-vs-semi-frameless-shower-doors.html'
      path: '/frameless-vs-semi-frameless-shower-doors.html'
      fullPath: '/frameless-vs-semi-frameless-shower-doors.html'
      preLoaderRoute: typeof FramelessVsSemiFramelessShowerDoorsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-shower-glass.html': {
      id: '/custom-shower-glass.html'
      path: '/custom-shower-glass.html'
      fullPath: '/custom-shower-glass.html'
      preLoaderRoute: typeof CustomShowerGlassDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-shower-glass-guide.html': {
      id: '/custom-shower-glass-guide.html'
      path: '/custom-shower-glass-guide.html'
      fullPath: '/custom-shower-glass-guide.html'
      preLoaderRoute: typeof CustomShowerGlassGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-remodel-glass.html': {
      id: '/bathroom-remodel-glass.html'
      path: '/bathroom-remodel-glass.html'
      fullPath: '/bathroom-remodel-glass.html'
      preLoaderRoute: typeof BathroomRemodelGlassDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-remodel-glass-guide.html': {
      id: '/bathroom-remodel-glass-guide.html'
      path: '/bathroom-remodel-glass-guide.html'
      fullPath: '/bathroom-remodel-glass-guide.html'
      preLoaderRoute: typeof BathroomRemodelGlassGuideDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BathroomRemodelGlassGuideDothtmlRoute: BathroomRemodelGlassGuideDothtmlRoute,
  BathroomRemodelGlassDothtmlRoute: BathroomRemodelGlassDothtmlRoute,
  CustomShowerGlassGuideDothtmlRoute: CustomShowerGlassGuideDothtmlRoute,
  CustomShowerGlassDothtmlRoute: CustomShowerGlassDothtmlRoute,
  FramelessVsSemiFramelessShowerDoorsDothtmlRoute:
    FramelessVsSemiFramelessShowerDoorsDothtmlRoute,
  GlassRailingsBuyersGuideDothtmlRoute: GlassRailingsBuyersGuideDothtmlRoute,
  GlassRailingsDothtmlRoute: GlassRailingsDothtmlRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
  MirrorsBuyersGuideDothtmlRoute: MirrorsBuyersGuideDothtmlRoute,
  MirrorsDothtmlRoute: MirrorsDothtmlRoute,
  OfficePartitionsGuideDothtmlRoute: OfficePartitionsGuideDothtmlRoute,
  OfficePartitionsDothtmlRoute: OfficePartitionsDothtmlRoute,
  OtherCustomGlassGuideDothtmlRoute: OtherCustomGlassGuideDothtmlRoute,
  OtherCustomGlassDothtmlRoute: OtherCustomGlassDothtmlRoute,
  RemodelingDothtmlRoute: RemodelingDothtmlRoute,
  ReplacementGlassGuideDothtmlRoute: ReplacementGlassGuideDothtmlRoute,
  ReplacementGlassDothtmlRoute: ReplacementGlassDothtmlRoute,
  ShowerDoorBuyersGuideDothtmlRoute: ShowerDoorBuyersGuideDothtmlRoute,
  ShowerDoorsArlingtonHeightsIlDothtmlRoute:
    ShowerDoorsArlingtonHeightsIlDothtmlRoute,
  ShowerDoorsBannockburnIlDothtmlRoute: ShowerDoorsBannockburnIlDothtmlRoute,
  ShowerDoorsBartlettIlDothtmlRoute: ShowerDoorsBartlettIlDothtmlRoute,
  ShowerDoorsBuffaloGroveIlDothtmlRoute: ShowerDoorsBuffaloGroveIlDothtmlRoute,
  ShowerDoorsDeerfieldIlDothtmlRoute: ShowerDoorsDeerfieldIlDothtmlRoute,
  ShowerDoorsDesPlainesIlDothtmlRoute: ShowerDoorsDesPlainesIlDothtmlRoute,
  ShowerDoorsElkGroveVillageIlDothtmlRoute:
    ShowerDoorsElkGroveVillageIlDothtmlRoute,
  ShowerDoorsEvanstonIlDothtmlRoute: ShowerDoorsEvanstonIlDothtmlRoute,
  ShowerDoorsGlencoeIlDothtmlRoute: ShowerDoorsGlencoeIlDothtmlRoute,
  ShowerDoorsGlenviewIlDothtmlRoute: ShowerDoorsGlenviewIlDothtmlRoute,
  ShowerDoorsHanoverParkIlDothtmlRoute: ShowerDoorsHanoverParkIlDothtmlRoute,
  ShowerDoorsHighlandParkIlDothtmlRoute: ShowerDoorsHighlandParkIlDothtmlRoute,
  ShowerDoorsHoffmanEstatesIlDothtmlRoute:
    ShowerDoorsHoffmanEstatesIlDothtmlRoute,
  ShowerDoorsLakeForestIlDothtmlRoute: ShowerDoorsLakeForestIlDothtmlRoute,
  ShowerDoorsLibertyvilleIlDothtmlRoute: ShowerDoorsLibertyvilleIlDothtmlRoute,
  ShowerDoorsLincolnshireIlDothtmlRoute: ShowerDoorsLincolnshireIlDothtmlRoute,
  ShowerDoorsMountProspectIlDothtmlRoute:
    ShowerDoorsMountProspectIlDothtmlRoute,
  ShowerDoorsNorthbrookIlDothtmlRoute: ShowerDoorsNorthbrookIlDothtmlRoute,
  ShowerDoorsNorthfieldIlDothtmlRoute: ShowerDoorsNorthfieldIlDothtmlRoute,
  ShowerDoorsPalatineIlDothtmlRoute: ShowerDoorsPalatineIlDothtmlRoute,
  ShowerDoorsParkRidgeIlDothtmlRoute: ShowerDoorsParkRidgeIlDothtmlRoute,
  ShowerDoorsRiverwoodsIlDothtmlRoute: ShowerDoorsRiverwoodsIlDothtmlRoute,
  ShowerDoorsRollingMeadowsIlDothtmlRoute:
    ShowerDoorsRollingMeadowsIlDothtmlRoute,
  ShowerDoorsRoselleIlDothtmlRoute: ShowerDoorsRoselleIlDothtmlRoute,
  ShowerDoorsSkokieIlDothtmlRoute: ShowerDoorsSkokieIlDothtmlRoute,
  ShowerDoorsStreamwoodIlDothtmlRoute: ShowerDoorsStreamwoodIlDothtmlRoute,
  ShowerDoorsVernonHillsIlDothtmlRoute: ShowerDoorsVernonHillsIlDothtmlRoute,
  ShowerDoorsWheelingIlDothtmlRoute: ShowerDoorsWheelingIlDothtmlRoute,
  ShowerDoorsWilmetteIlDothtmlRoute: ShowerDoorsWilmetteIlDothtmlRoute,
  ShowerDoorsWinnetkaIlDothtmlRoute: ShowerDoorsWinnetkaIlDothtmlRoute,
  ShowerDoorsDothtmlRoute: ShowerDoorsDothtmlRoute,
  ShowerEnclosureBuyersGuideDothtmlRoute:
    ShowerEnclosureBuyersGuideDothtmlRoute,
  ShowerEnclosuresDothtmlRoute: ShowerEnclosuresDothtmlRoute,
  TubDoorBuyersGuideDothtmlRoute: TubDoorBuyersGuideDothtmlRoute,
  TubDoorsDothtmlRoute: TubDoorsDothtmlRoute,
  WineCigarRoomGlassGuideDothtmlRoute: WineCigarRoomGlassGuideDothtmlRoute,
  WineCigarRoomsDothtmlRoute: WineCigarRoomsDothtmlRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
